### ISSUE TITLE
RECOMMENDATION: Adding the Option for SCAVs to be Affected by the Tier 7 Only Configuration 

### ISSUE THREAD

**Issue by TheRazgrizXX** [acidphantasm/acidphantasm-apbs#41]
Just as the title says, the recommendation I offer is to make it to where not only are PMCs (BEAR and USEC) are affected by the “Tier 7 Only” configuration, but even the SCAVs as well. I know it may sound odd, but the main reason why I am proposing such a recommendation is in terms of balance for such a configuration. If a player uses the Tier 7 mode, the PMCs are practically invulnerable against SCAVs and the only way the SCAVs have a chance is by either having more people (like a 3v1) or getting really lucky. With such a proposed recommendation, SCAVs now have a fighting chance against PMC AI and they are also an even greater threat to the player in general, assuming one wants to enable such a configuration.

**Comment by acidphantasm** [comment]
Added with:

Allow scavs to have equal equipment weights for every slot via config (allows them to use good gear at a much higher rate): https://github.com/acidphantasm/acidphantasm-apbs/commit/b949471cf0533b68b31767e343e4525fbbd009af
The above commit is probably going to be really wonky, it's a lot of effort to allow specific things to be changed instead of just making the entire pool equal.

Allow scavs to use tiered attachments via config: https://github.com/acidphantasm/acidphantasm-apbs/commit/0e1d461958ed3bd437420f349b7fcf6d2bf4f4ae
